### ISSUE TITLE
Websocket Reconnection Failes

### ISSUE THREAD

**Issue by baloian** [bennyn/coinbase-pro-node#107]
Hi @bennyn I am still having a reconnection issue though I changed `connect()` parameters.

So, at some point websocket establishes connection and then closes, and this run as a loop. On `ON_OPEN` it shows that it establishes connect and just after that `ON_CLOSE` it says convection closed and repeats the same. I have to manually stop and run program in order to make it work.

Any recommendation and/or suggestion? should I subscribe every time when it reconnects again?

**Comment by bennyn** [comment]
Hey, can you show me your code? I will try to reproduce this problem on my machine.

**Comment by baloian** [comment]
Please have look at the [source code](https://github.com/baloian/cetracker/blob/master/exchanges/coinbase/coinbase_pro.mjs).

Thanks for helping me out.

**Comment by bennyn** [comment]
Ok, I already see some issues here:
1. You cannot use `this.client.ws.unsubscribe` when receiving a `WebSocketEvent.ON_CLOSE` event because the WebSocket is closed so the `unsubscribe` message cannot be send through the WebSocket anymore
1. You still do `await this.client.ws.connect` but `connect` is not a `Promise` anymore since v1.6.0
1. You don't have to call `client.ws.subscribe([this.channel])` after `this.client.ws.connect` because you are doing this already in your `WebSocketEvent.ON_OPEN` handler
1. I am not sure if `this.client.ws.subscribe` is necessary on every `WebSocketEvent.ON_OPEN`, I would guess you only need to do it for the very first `ON_OPEN`, can you confirm?

**Comment by baloian** [comment]
I had the issue even before adding `1.` , `3.` and `4.` One commit before the latest commit.

**Comment by baloian** [comment]
I updated the code based on `2.` and cleaned up `1.`, `3.` and `4.`. Let me run again and see how it goes. I also want to do some debugging so I can give you reason(s) why it happens.

**Comment by bennyn** [comment]
Hey @baloian, thanks for your intensive testing. You can test against the [official coinbase-pro](https://github.com/coinbase/coinbase-pro-node) library. It is deprecated but should still be able to connect to the WebSocket. If the problem also shows up with their library, then it tends to be a server issue.

**Comment by baloian** [comment]
That is a good idea. I will come back to testing in 2 weeks probably as I have some deadlines on my work.

**Comment by bennyn** [comment]
Great. Good luck with your deadlines. 🍀
