### ISSUE TITLE
Is this an official repo?

### ISSUE THREAD

**Issue by TheRyanMiller** [bennyn/coinbase-pro-node#188]
I understand two node packages with official Coinbase support appear to now be deprecated. Was there a state reason why it was deprecated? Can you please describe the support that this repo here has if official or not?

**Comment by bennyn** [comment]
Hi @TheRyanMiller, I am happy that you are interested in my library. 

The motiviation behind my library is explained [in the readme file](https://github.com/bennyn/coinbase-pro-node#motivation). It's my attempt to maintain an active Coinbase Pro API for Node.js. It's not official since I'm not a Coinbase employee.

I don't know the reason why the [official API](https://github.com/coinbase/coinbase-pro-node) was deprecated. 😞
