### ISSUE TITLE
getProductHistoricRates function?

### ISSUE THREAD

**Issue by bfailing** [bennyn/coinbase-pro-node#93]
What is the equivalent in your library to the following code from the [coinbase-pro](https://github.com/coinbase/coinbase-pro-node) library:
````
publicClient.getProductHistoricRates(
  'BTC-USD',
  { 
    granularity: 3600,
    start: start_time,
    end: end_time
  }  
)
````

**Comment by bennyn** [comment]
Hi @bfailing, the product history data at Coinbase Pro is actually what everybody else (like Binance exchange) calls "candlesticks". That's why this library here makes it available with:

```typescript
client.rest.product.getCandles('BTC-USD', {
  granularity: CandleGranularity.ONE_HOUR,
  start: start_time,
  end: end_time
});
```

I hope this helps you further. Please [leave a star](https://github.com/bennyn/coinbase-pro-node/stargazers) if it does. If not, you can create [a new issue](https://github.com/bennyn/coinbase-pro-node/issues/new) and I will help you with it.
